_wandb:
    value:
        cli_version: 0.25.0
        e:
            8huwv35oc1dd34n4g3p47comidxhlofq:
                args:
                    - --wandb_entity
                    - ma24m0-iit-madras
                    - --wandb_project
                    - mnist-ann
                codePath: src\fashion_mnist.py
                codePathLocal: fashion_mnist.py
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "498949156864"
                        used: "214292316160"
                email: ma24m014@smail.iitm.ac.in
                executable: C:\Users\hp\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 184aeffc46d91efeae462b80193dd14d98bb2e86
                    remote: https://github.com/KRITIKA-GAHLAWAT/deep-learning-assignment1.git
                host: DESKTOP-68MTNN0
                memory:
                    total: "16858472448"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\hp\dl_project\assignment\deep-learning-assignment1\src\fashion_mnist.py
                python: CPython 3.13.1
                root: C:\Users\hp\dl_project\assignment\deep-learning-assignment1\src
                startedAt: "2026-03-07T13:21:40.128254Z"
                writerId: 8huwv35oc1dd34n4g3p47comidxhlofq
        m: []
        python_version: 3.13.1
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.13.1
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation_function:
    value: relu
batch_size:
    value: 128
dataset:
    value: fashion_mnist
epochs:
    value: 10
initialization_method:
    value: he
input_dim:
    value: 784
learning_rate:
    value: 0.01
num_hidden_layers:
    value: 3
num_neurons:
    value: "512"
num_neurons_resolved:
    value: "512"
optimizer:
    value: nadam
output_dim:
    value: 10
random_seed:
    value: 42
val_ratio:
    value: 0.1
weight_decay:
    value: 0.0001
